// <auto-generated />
using System;
using AniMan.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AniMan.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("AniMan.Core.Domain.Models.CachedAnime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiringEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiringStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverLargeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverMediumUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Popularity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("Season")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studios")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleJapanese")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.CachedAnimeStreaming", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("AnimeStreaming");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.CachedEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleJapanese")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.CachedGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.CachedManga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverLargeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverMediumUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Popularity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublishedEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedStart")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("Serializations")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleJapanese")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalChapters")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalVolumes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manga");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.CachedMediaGenre", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CachedAnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CachedMangaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaId", "MediaType", "GenreId");

                    b.HasIndex("CachedAnimeId");

                    b.HasIndex("CachedMangaId");

                    b.HasIndex("GenreId");

                    b.ToTable("MediaGenres");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.CachedAnimeStreaming", b =>
                {
                    b.HasOne("AniMan.Core.Domain.Models.CachedAnime", "Anime")
                        .WithMany("StreamingPlatforms")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.CachedEpisode", b =>
                {
                    b.HasOne("AniMan.Core.Domain.Models.CachedAnime", "Anime")
                        .WithMany("Episodes")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.CachedMediaGenre", b =>
                {
                    b.HasOne("AniMan.Core.Domain.Models.CachedAnime", null)
                        .WithMany("MediaGenres")
                        .HasForeignKey("CachedAnimeId");

                    b.HasOne("AniMan.Core.Domain.Models.CachedManga", null)
                        .WithMany("MediaGenres")
                        .HasForeignKey("CachedMangaId");

                    b.HasOne("AniMan.Core.Domain.Models.CachedGenre", "Genre")
                        .WithMany("MediaGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.CachedAnime", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("MediaGenres");

                    b.Navigation("StreamingPlatforms");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.CachedGenre", b =>
                {
                    b.Navigation("MediaGenres");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.CachedManga", b =>
                {
                    b.Navigation("MediaGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
