// <auto-generated />
using System;
using AniMan.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AniMan.Migrations.LibraryDb
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260726161715_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("AniMan.Core.Domain.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.ChapterProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryItemId", "ChapterNumber")
                        .IsUnique();

                    b.ToTable("ChapterProgress");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.EpisodeProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryItemId", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("EpisodeProgress");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.LibraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastRewatchDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RewatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UserRating")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("MalId", "MediaType")
                        .IsUnique();

                    b.ToTable("LibraryItems");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.MediaSnapshot", b =>
                {
                    b.Property<int>("LibraryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiringEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiringStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverOriginalUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("MalScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Season")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamingPlatforms")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleJapanese")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalChapters")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalVolumes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("LibraryItemId");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryItemId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.TrackingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TrackingStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsDefault = true,
                            Name = "Watching"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            IsDefault = true,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            IsDefault = true,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 3,
                            IsDefault = true,
                            Name = "On-hold"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 4,
                            IsDefault = true,
                            Name = "Dropped"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 5,
                            IsDefault = true,
                            Name = "Plan to watch"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 5,
                            IsDefault = true,
                            Name = "Plan to read"
                        });
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.UserStreamingOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryItemId");

                    b.ToTable("StreamingOverrides");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.ChapterProgress", b =>
                {
                    b.HasOne("AniMan.Core.Domain.Models.LibraryItem", "LibraryItem")
                        .WithMany("ChapterProgress")
                        .HasForeignKey("LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryItem");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.EpisodeProgress", b =>
                {
                    b.HasOne("AniMan.Core.Domain.Models.LibraryItem", "LibraryItem")
                        .WithMany("EpisodeProgress")
                        .HasForeignKey("LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryItem");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.LibraryItem", b =>
                {
                    b.HasOne("AniMan.Core.Domain.Models.TrackingStatus", "Status")
                        .WithMany("LibraryItems")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.MediaSnapshot", b =>
                {
                    b.HasOne("AniMan.Core.Domain.Models.LibraryItem", "LibraryItem")
                        .WithOne("Snapshot")
                        .HasForeignKey("AniMan.Core.Domain.Models.MediaSnapshot", "LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryItem");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.Note", b =>
                {
                    b.HasOne("AniMan.Core.Domain.Models.LibraryItem", "LibraryItem")
                        .WithMany("Notes")
                        .HasForeignKey("LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryItem");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.UserStreamingOverride", b =>
                {
                    b.HasOne("AniMan.Core.Domain.Models.LibraryItem", "LibraryItem")
                        .WithMany("StreamingOverrides")
                        .HasForeignKey("LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryItem");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.LibraryItem", b =>
                {
                    b.Navigation("ChapterProgress");

                    b.Navigation("EpisodeProgress");

                    b.Navigation("Notes");

                    b.Navigation("Snapshot");

                    b.Navigation("StreamingOverrides");
                });

            modelBuilder.Entity("AniMan.Core.Domain.Models.TrackingStatus", b =>
                {
                    b.Navigation("LibraryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
